# Generated by Django 4.2.30 on 2026-05-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('resultados', models.TextField(blank=True, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
