# Generated by Django 4.2.30 on 2026-05-08 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_registradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
