# Generated by Django 4.2.30 on 2026-05-08 07:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo se permiten letras.')])),
                ('apellido_paterno', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo se permiten letras.')])),
                ('apellido_materno', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo se permiten letras.')])),
                ('apellidos', models.CharField(blank=True, editable=False, max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('sala', models.CharField(blank=True, choices=[('LACTANTES', 'Lactantes'), ('INFANTE I', 'Infante I'), ('INFANTE II A', 'Infante II A'), ('INFANTE II B', 'Infante II B')], max_length=20, null=True)),
                ('info_medica', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ninos/fotos/')),
                ('fecha_ingreso', models.DateField()),
                ('CI_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ninos', to='beneficiarios.beneficiario')),
                ('id_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ninos', to='grupos.grupo')),
            ],
            options={
                'verbose_name': 'Niño',
                'verbose_name_plural': 'Niños',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
    ]
