# Generated by Django 4.2.30 on 2026-05-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0007_alter_tutorpadre_beneficiario'),
        ('ninos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='CI_tutor_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ninos', to='beneficiarios.tutorpadre'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='CI_beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ninos', to='beneficiarios.beneficiario'),
        ),
    ]
