# Generated by Django 4.2.30 on 2026-05-08 07:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('CI_beneficiario', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo letras.')])),
                ('apellido_paterno', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo letras.')])),
                ('apellido_materno', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo letras.')])),
                ('apellidos', models.CharField(blank=True, editable=False, max_length=100)),
                ('ocupacion', models.CharField(choices=[('ESTUDIANTE_ITDB', 'Estudiante ITDB'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('contacto', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo números.')])),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='beneficiarios/fotos/')),
                ('documentos_adjuntos', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_nino', models.CharField(max_length=100)),
                ('fecha_nacimiento_nino', models.DateField()),
                ('nombres_tutor', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('estado', models.CharField(default='pendiente', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TutorPadre',
            fields=[
                ('CI_tutor', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo letras.')])),
                ('apellido_paterno', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo letras.')])),
                ('contacto', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo números.')])),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='beneficiarios.beneficiario')),
            ],
        ),
    ]
