# Generated by Django 4.2.30 on 2026-05-08 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preinscripcion',
            options={'verbose_name': 'Pre-inscripción', 'verbose_name_plural': 'Pre-inscripciones'},
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='CI_tutor',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='apellido_materno_nino',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='apellido_paterno_nino',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='apellido_paterno_tutor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='observaciones_resolucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10),
        ),
    ]
