# Generated by Django 4.2.30 on 2026-05-08 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0002_alter_preinscripcion_options_preinscripcion_ci_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorpadre',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Solo letras.')]),
        ),
    ]
