# Generated by Django 4.2.30 on 2026-05-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0003_tutorpadre_apellido_materno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorpadre',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tutorpadre',
            name='ocupacion',
            field=models.CharField(choices=[('ESTUDIANTE_ITDB', 'Estudiante ITDB'), ('OTRO', 'Otro')], default='OTRO', max_length=30),
        ),
    ]
