# Generated by Django 4.2.30 on 2026-05-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0004_tutorpadre_direccion_tutorpadre_ocupacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='anio_semestre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='carrera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='ocupacion_especifica',
            field=models.CharField(blank=True, help_text='Especificar si es comerciante, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='turno',
            field=models.CharField(blank=True, choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tutorpadre',
            name='anio_semestre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutorpadre',
            name='carrera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutorpadre',
            name='ocupacion_especifica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutorpadre',
            name='turno',
            field=models.CharField(blank=True, choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], max_length=15, null=True),
        ),
    ]
