# Generated by Django 4.2.30 on 2026-05-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0006_beneficiario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorpadre',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutores', to='beneficiarios.beneficiario'),
        ),
    ]
