# Generated by Django 4.2.30 on 2026-05-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0007_alter_tutorpadre_beneficiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorpadre',
            name='documentos_adjuntos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorpadre',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='tutores/fotos/'),
        ),
    ]
