# Generated by Django 4.2.30 on 2026-05-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0008_tutorpadre_documentos_adjuntos_tutorpadre_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion',
            name='anio_semestre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='apellido_materno_tutor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='carrera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='foto_nino',
            field=models.ImageField(blank=True, null=True, upload_to='preinscripciones/fotos/'),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='ocupacion',
            field=models.CharField(choices=[('ESTUDIANTE_ITDB', 'Estudiante ITDB'), ('OTRO', 'Otro')], default='OTRO', max_length=30),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='ocupacion_descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='sala_solicitada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='sexo_nino',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='turno',
            field=models.CharField(blank=True, choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], max_length=15, null=True),
        ),
    ]
