# Generated by Django 4.2.11 on 2026-05-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0010_documento_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='ocupacion',
            field=models.CharField(choices=[('ESTUDIANTE_ITDB', 'Estudiante ITDB')], default='ESTUDIANTE_ITDB', max_length=30),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='ocupacion_especifica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='ocupacion',
            field=models.CharField(choices=[('COSTURA', 'Costura'), ('ALBAÑIL', 'Albañil'), ('COMERCIANTE', 'Comerciante'), ('EMPLEADO', 'Empleado'), ('OBRERO', 'Obrero'), ('PROFESIONAL', 'Profesional'), ('VENDEDOR', 'Vendedor'), ('ARTESANO', 'Artesano'), ('TRANSPORTISTA', 'Transportista'), ('AGRICULTOR', 'Agricultor'), ('OTRO', 'Otro')], default='OTRO', max_length=30),
        ),
        migrations.AlterField(
            model_name='tutorpadre',
            name='ocupacion',
            field=models.CharField(choices=[('COSTURA', 'Costura'), ('ALBAÑIL', 'Albañil'), ('COMERCIANTE', 'Comerciante'), ('EMPLEADO', 'Empleado'), ('OBRERO', 'Obrero'), ('PROFESIONAL', 'Profesional'), ('VENDEDOR', 'Vendedor'), ('ARTESANO', 'Artesano'), ('TRANSPORTISTA', 'Transportista'), ('AGRICULTOR', 'Agricultor'), ('OTRO', 'Otro')], default='OTRO', max_length=30),
        ),
    ]
